### PR TITLE
feat(queries): Add RUM Dashboard

### PR DESCRIPTION
**Pull request by trieloff**
adds a query that extracts share of good (according to Google limits) CWV values, average CWV values, estimated number of page views, and estimated share of total RUM traffic for the current and previous 30 day period for an owner-repo pair, a domain name, or all domains with Helix RUM collection set up

## Example Responses

```bash
$ cat src/queries/rum-dashboard.sql | bq query --use_legacy_sql=false --format=prettyjson --parameter domain::- --parameter owner::- --parameter repo::- --parameter limit:INT64:3
```

```jsonc
[
  {
    "avgcls": "0.011", // average CLS for the current period
    "avgcls_1": "0.038", // average CLS for the previous period
    "avgfid": "2", 
    "avgfid_1": "2", 
    "avglcp": "912", 
    "avglcp_1": "904", 
    "clsgood": "68", // percentage of page views that result in a "good" CLS, according to Google in the current period
    "clsgood_1": "57", 
    "fidpgood": "96", 
    "fidpgood_1": "97", 
    "lcpgood": "84", 
    "lcpgood_1": "84", 
    "pageviews": "1346100", // estimated number of page views in the current period
    "pageviews_1": "1381200", 
    "rumshare": "87.968835467", // estimated share of this domain on all RUM traffic (can be used for cost modeling)
    "rumshare_1": "87.174900798", 
    "url": "blog.adobe.com" // the domain - using dashes for all filter parameters enables domain-wide tracking
  }, 
  {
    "avgcls": "0.126", 
    "avgcls_1": "0.157", 
    "avgfid": "2", 
    "avgfid_1": "3", 
    "avglcp": "5295", 
    "avglcp_1": "5768", 
    "clsgood": "40", 
    "clsgood_1": "40", 
    "fidpgood": "100", 
    "fidpgood_1": "100", 
    "lcpgood": "25", 
    "lcpgood_1": "3", 
    "pageviews": "135900", 
    "pageviews_1": "160700", 
    "rumshare": "8.881186197", 
    "rumshare_1": "10.142634346", 
    "url": "theblog--adobe.hlx.page"
  }, 
  {
    "avgcls": null, 
    "avgcls_1": null, 
    "avgfid": null, 
    "avgfid_1": null, 
    "avglcp": null, 
    "avglcp_1": null, 
    "clsgood": null, 
    "clsgood_1": null, 
    "fidpgood": null, 
    "fidpgood_1": null, 
    "lcpgood": null, 
    "lcpgood_1": null, 
    "pageviews": "42400", 
    "pageviews_1": "40100", 
    "rumshare": "2.770877813", 
    "rumshare_1": "2.530924936", 
    "url": "theblog--adobe.hlx.live"
  }, 
  {
    "avgcls": "0.097", 
    "avgcls_1": "0.094", 
    "avgfid": "4", 
    "avgfid_1": "0", 
    "avglcp": "4767", 
    "avglcp_1": "5628", 
    "clsgood": "45", 
    "clsgood_1": "42", 
    "fidpgood": "77", 
    "fidpgood_1": "29", 
    "lcpgood": "25", 
    "lcpgood_1": "17", 
    "pageviews": "5801", 
    "pageviews_1": "2401", 
    "rumshare": "0.379100523", 
    "rumshare_1": "0.15153992", 
    "url": "Other"
  }
]
```

```bash
$ cat src/queries/rum-dashboard.sql | bq query --use_legacy_sql=false --format=prettyjson --parameter domain::blog.adobe.com --parameter owner::adobe --parameter repo::theblog --parameter limit:INT64:10
```

```json
[
  {
    "avgcls": "0.009", 
    "avgcls_1": "0.038", 
    "avgfid": "2", 
    "avgfid_1": "2", 
    "avglcp": "1171", 
    "avglcp_1": "1193", 
    "clsgood": "73", 
    "clsgood_1": "54", 
    "fidpgood": "96", 
    "fidpgood_1": "95", 
    "lcpgood": "83", 
    "lcpgood_1": "81", 
    "pageviews": "279200", 
    "pageviews_1": "310500", 
    "rumshare": "18.243584525", 
    "rumshare_1": "19.596074726", 
    "url": "https://blog.adobe.com/en/publish/2019/05/30/the-future-of-adobe-air.html"
  }, 
  {
    "avgcls": "0.001", 
    "avgcls_1": "0.001", 
    "avgfid": "3", 
    "avgfid_1": "3", 
    "avglcp": "826", 
    "avglcp_1": "936", 
    "clsgood": "95", 
    "clsgood_1": "97", 
    "fidpgood": "95", 
    "fidpgood_1": "97", 
    "lcpgood": "86", 
    "lcpgood_1": "83", 
    "pageviews": "96600", 
    "pageviews_1": "96000", 
    "rumshare": "6.31207115", 
    "rumshare_1": "6.05868977", 
    "url": "https://blog.adobe.com/"
  }, 
  {
    "avgcls": null, 
    "avgcls_1": null, 
    "avgfid": null, 
    "avgfid_1": null, 
    "avglcp": null, 
    "avglcp_1": null, 
    "clsgood": null, 
    "clsgood_1": null, 
    "fidpgood": null, 
    "fidpgood_1": null, 
    "lcpgood": null, 
    "lcpgood_1": null, 
    "pageviews": "41400", 
    "pageviews_1": "44300", 
    "rumshare": "2.70517335", 
    "rumshare_1": "2.795832884", 
    "url": "https://theblog--adobe.hlx.page/"
  }, 
  {
    "avgcls": "0.131", 
    "avgcls_1": "0.197", 
    "avgfid": "3", 
    "avgfid_1": "2", 
    "avglcp": "963", 
    "avglcp_1": "1115", 
    "clsgood": "17", 
    "clsgood_1": "9", 
    "fidpgood": "95", 
    "fidpgood_1": "94", 
    "lcpgood": "88", 
    "lcpgood_1": "87", 
    "pageviews": "31800", 
    "pageviews_1": "41000", 
    "rumshare": "2.077886776", 
    "rumshare_1": "2.587565423", 
    "url": "https://blog.adobe.com/en/publish/2017/07/25/adobe-flash-update.html"
  }, 
  {
    "avgcls": null, 
    "avgcls_1": null, 
    "avgfid": null, 
    "avgfid_1": null, 
    "avglcp": null, 
    "avglcp_1": null, 
    "clsgood": null, 
    "clsgood_1": null, 
    "fidpgood": null, 
    "fidpgood_1": null, 
    "lcpgood": null, 
    "lcpgood_1": null, 
    "pageviews": "42300", 
    "pageviews_1": "39900", 
    "rumshare": "2.763981466", 
    "rumshare_1": "2.518142936", 
    "url": "https://theblog--adobe.hlx.live/"
  }, 
  {
    "avgcls": "0.002", 
    "avgcls_1": "0.002", 
    "avgfid": "3", 
    "avgfid_1": "2", 
    "avglcp": "784", 
    "avglcp_1": "727", 
    "clsgood": "94", 
    "clsgood_1": "95", 
    "fidpgood": "95", 
    "fidpgood_1": "100", 
    "lcpgood": "87", 
    "lcpgood_1": "92", 
    "pageviews": "27200", 
    "pageviews_1": "24400", 
    "rumshare": "1.777311959", 
    "rumshare_1": "1.539916983", 
    "url": "https://blog.adobe.com/404.html"
  }, 
  {
    "avgcls": "0.029", 
    "avgcls_1": "0.03", 
    "avgfid": "3", 
    "avgfid_1": "2", 
    "avglcp": "547", 
    "avglcp_1": "582", 
    "clsgood": "95", 
    "clsgood_1": "95", 
    "fidpgood": "91", 
    "fidpgood_1": "95", 
    "lcpgood": "86", 
    "lcpgood_1": "89", 
    "pageviews": "23500", 
    "pageviews_1": "23900", 
    "rumshare": "1.535545259", 
    "rumshare_1": "1.508361307", 
    "url": "https://blog.adobe.com/en/topics/creative-cloud.html"
  }, 
  {
    "avgcls": "0.048", 
    "avgcls_1": "0.054", 
    "avgfid": "2", 
    "avgfid_1": "2", 
    "avglcp": "314", 
    "avglcp_1": "239", 
    "clsgood": "95", 
    "clsgood_1": "97", 
    "fidpgood": "98", 
    "fidpgood_1": "93", 
    "lcpgood": "99", 
    "lcpgood_1": "96", 
    "pageviews": "22000", 
    "pageviews_1": "21700", 
    "rumshare": "1.437531732", 
    "rumshare_1": "1.369516334", 
    "url": "https://blog.adobe.com/en/topics/news.html"
  }, 
  {
    "avgcls": "0.036", 
    "avgcls_1": "0.062", 
    "avgfid": "5", 
    "avgfid_1": "4", 
    "avglcp": "796", 
    "avglcp_1": "754", 
    "clsgood": "46", 
    "clsgood_1": "39", 
    "fidpgood": "47", 
    "fidpgood_1": "49", 
    "lcpgood": "58", 
    "lcpgood_1": "59", 
    "pageviews": "907600", 
    "pageviews_1": "917800", 
    "rumshare": "59.304718175", 
    "rumshare_1": "57.92359866", 
    "url": "Other"
  }
]
```

### CODE REVIEW

**Review by tripodsan — APPROVED** [review]

**Comment by trieloff** [comment]
@kptdobe can you spot check the data format – would that make sense to you?

**Comment by kptdobe** [comment]
I am not sure about the `*good` entries, since "good" is debatable. For "us", a "good" CLS must be 0 while Google makes it green when less than 0.1.

**Comment by kptdobe** [comment]
Not sure I understand the need for the RUM share. It is correlated to the traffic (more traffic, more RUM requests, increase of the RUM share).

**Comment by trieloff** [comment]
The idea of the rum share is the following: eventually all billed Helix traffic will have RUM monitoring in place. We know the total cost of running Helix and we can divide it among the sites according to their traffic share. In a pure performance dashboard we would not show it.

**Pull request merged**
