### PR TITLE
[Domain-list] hostname in response is not unique #1120

### PR DESCRIPTION
**Pull request by lydiapuric**
Please ensure your pull request adheres to the following guidelines:
- [x] make sure to link the related issues in this description
- [x] when merging / squashing, make sure the fixed issue references are visible in the commits, for easy compilation of release notes

## Related Issues
 [Domain-list] hostname in response is not unique #1120 

Thanks for reviewing!

### CODE REVIEW

**Review by langswei — APPROVED** [review]
Good catch.  I wonder if maybe line 49 is where this was introduced, and an earlier (read: more appropriate) place to add DISTINCT.  I have noticed the `@v3` query sometimes times out now.  Anyways, approving and you can choose to merge as-is or investigate further.  You are the only consumer of this query, as far as I know.

**Comment by lydiapuric** [comment]
@langswei Just checked, thx. You are right, the DISTINCT in earlier place in line 49 is the right place to be, adjusting.

**Comment by langswei** [comment]
@lydiapuric I still see duplicates, but at least it's faster.  Perhaps the answer is to have DISTINCT in both places.  I will also speculate that this problem will go away over time -- earlier records did not have p###-e###, newer records do.  Eventually the old ones will fall out of the query, but not until 2025 sometime so it's probably worth fixing.

**Comment by lydiapuric** [comment]
@langswei, I don't see duplicates. I made a count by hostname at the end. It looks good to me. and regarding records which did not have p###-e###, newer records do: in line 54 restrict to pattern and in line 97 i do only a join at hostname. so even if prior records have not the pattern, they will get assigned to the new cs values.

**Pull request merged**
